import Lean.Elab.Command

/-!
# Tests for whitespace generated by the pretty-printer.
-/

elab "#pp " cmd:command : command => Lean.logInfo cmd

/-- info: example (h : False) : False := by rcases (h) -/
#guard_msgs in #pp
example (h : False) : False := by
  rcases (h)

structure X where
  A : {_ : Nat} → Nat → Nat

/-- info: example : X where A {a} b := a + b -/
#guard_msgs in #pp
example : X where
  A {a} b := a + b

/--
info: example : True :=
  have (h) := trivial
  h
-/
#guard_msgs in #pp
example : True :=
  have (h) := trivial
  h

/--
info: example : True := by
  have (h) := trivial
  exact h
-/
#guard_msgs in #pp
example : True := by
  have (h) := trivial
  exact h

/--
info: example (h : ∀ a : Nat, a = a) : 0 = 0 := by
  replace (h) := h 0
  exact h
-/
#guard_msgs in #pp
example (h : ∀ a : Nat, a = a) : 0 = 0 := by
  replace (h) := h 0
  exact h


/-- info: example : 0 = 0 := by simp!; -/
#guard_msgs in #pp
example : 0 = 0 := by
  simp!;
